name: Build

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      path_prefix:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      path_prefix: ${{ inputs.path_prefix || '' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
      - name: Install bundled gems
        run: bundle install
      - name: Build site
        run: bundle exec middleman build --verbose
      - name: Check HTML
        uses: anishathalye/proof-html@v2
        with:
          directory: ./build
          disable_external: true
