name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4"
      - name: Install bundled gems
        run: bundle install
      - name: Build site
        run: bundle exec middleman build --verbose
      - name: Check HTML
        uses: WispySparks/proof-html@disable_external-option
        with:
          directory: ./build
          disable_external: true
