name: Codespell

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
