name: Deploy

on:
  push:
    branches:
      - master

concurrency: deploy-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build website
        uses: ./.github/actions/build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build
          clean-exclude: pr-preview/
          force: false
