name: Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
      - name: Install bundler
        run: gem install bundler:2.1.4
      - name: Install bundled gems
        run: bundle install
      - name: Build site
        run: bundle exec middleman build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Build directory to deploy
          build_dir: ./build
          # Allow Jekyll to build your site
          #jekyll: # optional, default is true
