name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  call-build:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/build.yml
  preview:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
      - run: tar -cvf working_directory.tar .
      - uses: actions/upload-artifact@v4
        with:
          name: directory
          path: working_directory.tar
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
          # custom-url: frc2508.com
