name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      path_prefix: pr-preview/pr-${{ github.event.number }}
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build
          custom-url: frc2508.com
